server:
  port: 8081

app:
  ai:
    provider: vertexai #openai

logging:
  level:
    root: INFO
    com.genai.java.spring: INFO
    org.springframework.ai: INFO
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

spring:
  application:
    name: gen-ai-java-spring
  openai:
    api-key: ${HUGGINGFACE_API_KEY} #${OPENAI_API_KEY}
    base-url: https://router.huggingface.co
    chat:
      options:
        model: Qwen/Qwen2.5-Coder-7B-Instruct:nscale # gpt-4o-mini # gpt-4o # gpt-5.2 # gpt-3.5-turbo # ai/gemma3 # mistral:7b # Qwen/Qwen2.5-Coder-7B-Instruct

#  vertex:
#    ai:
#      gemini:
#        project-id: your-google-project-id
#        location: us-central1
#        chat:
#          options:
#            model: gemini-2.0-flash
  huggingface:
    chat:
      api-key: ${HUGGINGFACE_API_KEY}
      url:
      options:
        model: Qwen/Qwen2.5-Coder-14B-Instruct-GGUF
        max-new-tokens: 1024
        temperature: 0.7

