server:
  port: 8081

logging:
  level:
    root: INFO
    com.genai.java.spring: INFO
    org.springframework.ai: INFO
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

spring:
  application:
    name: gen-ai-java-spring
  ai:
    chat:
      memory:
        repository:
          jdbc:
            # For local/dev, let Spring AI create the table automatically:
            initialize-schema: always # If not exists, It creates the default table spring_ai_chat_memory with columns (conversation_id, role, content, metadata, …) for window-based memory.
    openai:
      api-key: ${OPENAI_API_KEY} #dummy-string # ${HUGGINGFACE_API_KEY}
      #base-url: http://localhost:12434/engines/llama.cpp #https://router.huggingface.co # Not needed for OpenAI
      chat:
        options:
          model: gpt-4.1 #ai/gemma3 # Qwen/Qwen2.5-Coder-7B-Instruct:nscale # gpt-4o-mini # gpt-4o # gpt-5.2 # gpt-3.5-turbo # ai/gemma3 # mistral:7b # Qwen/Qwen2.5-Coder-7B-Instruct

      #  vertex:
      #    ai:
      #      gemini:
      #        project-id: your-google-project-id
      #        location: us-central1
      #        chat:
      #          options:
      #            model: gemini-2.0-flash
    huggingface:
      chat:
        api-key: ${HUGGINGFACE_API_KEY}
        url:
        options:
          model: Qwen/Qwen2.5-Coder-14B-Instruct-GGUF
          max-new-tokens: 1024
          temperature: 0.7
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: mistral:7b # custom-mistral-model:latest
          max-new-tokens: 512
          temperature: 0.7
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: postgres
    sql:
      init:
        mode: always
        data-locations: classpath:/db/data.sql

